// <auto-generated />
using System;
using CalorieProject_DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diet_DAL.Migrations
{
    [DbContext(typeof(DietDBContext))]
    partial class DietDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalorieProject_Models.Concretes.FoodCategory", b =>
                {
                    b.Property<int>("FoodCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodCategoryID"));

                    b.Property<string>("FoodCategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("FoodCategoryID");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            FoodCategoryID = 1,
                            FoodCategoryName = "Fruits"
                        },
                        new
                        {
                            FoodCategoryID = 2,
                            FoodCategoryName = "Vegetables"
                        },
                        new
                        {
                            FoodCategoryID = 3,
                            FoodCategoryName = "FastFoods"
                        },
                        new
                        {
                            FoodCategoryID = 4,
                            FoodCategoryName = "Cheeses"
                        },
                        new
                        {
                            FoodCategoryID = 5,
                            FoodCategoryName = "Meats"
                        },
                        new
                        {
                            FoodCategoryID = 6,
                            FoodCategoryName = "Sweets"
                        },
                        new
                        {
                            FoodCategoryID = 7,
                            FoodCategoryName = "Beverages"
                        },
                        new
                        {
                            FoodCategoryID = 8,
                            FoodCategoryName = "Cereals"
                        },
                        new
                        {
                            FoodCategoryID = 9,
                            FoodCategoryName = "Legumes"
                        },
                        new
                        {
                            FoodCategoryID = 10,
                            FoodCategoryName = "Edible oils and fats"
                        },
                        new
                        {
                            FoodCategoryID = 11,
                            FoodCategoryName = "Milk and milk products"
                        },
                        new
                        {
                            FoodCategoryID = 12,
                            FoodCategoryName = "Others"
                        });
                });

            modelBuilder.Entity("CalorieProject_Models.Concretes.Meal", b =>
                {
                    b.Property<int>("MealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealID"));

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("MealID");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            MealID = 1,
                            MealName = "Breakfast"
                        },
                        new
                        {
                            MealID = 2,
                            MealName = "Lunch"
                        },
                        new
                        {
                            MealID = 3,
                            MealName = "Dinner"
                        });
                });

            modelBuilder.Entity("CalorieProject_Models.Concretes.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<int>("ActivityStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<double>("CaloriesPerDay")
                        .HasColumnType("float");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserStatus")
                        .HasColumnType("int");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasMaxLength(250)
                        .HasColumnType("float");

                    b.HasKey("PersonID");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            ActivityStatus = 2,
                            BirthDate = new DateTime(1995, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CaloriesPerDay = 0.0,
                            FirstName = "Emre",
                            Gender = 1,
                            Height = 0.0,
                            LastName = "Bekfilavi",
                            Password = "1234",
                            UserName = "Admin1",
                            UserStatus = 1,
                            UserType = 2,
                            Weight = 85.5
                        },
                        new
                        {
                            PersonID = 2,
                            ActivityStatus = 2,
                            BirthDate = new DateTime(1995, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CaloriesPerDay = 0.0,
                            FirstName = "Barış",
                            Gender = 1,
                            Height = 0.0,
                            LastName = "Erdem",
                            Password = "12345",
                            UserName = "Admin2",
                            UserStatus = 1,
                            UserType = 2,
                            Weight = 85.5
                        },
                        new
                        {
                            PersonID = 3,
                            ActivityStatus = 2,
                            BirthDate = new DateTime(1995, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CaloriesPerDay = 0.0,
                            FirstName = "Recep",
                            Gender = 1,
                            Height = 0.0,
                            LastName = "Öztuna",
                            Password = "123456",
                            UserName = "Admin3",
                            UserStatus = 1,
                            UserType = 2,
                            Weight = 85.5
                        });
                });

            modelBuilder.Entity("Diet_Models.Concretes.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodID"));

                    b.Property<int>("Calories")
                        .HasMaxLength(1000)
                        .HasColumnType("integer");

                    b.Property<int>("FoodCategoryID")
                        .HasColumnType("int");

                    b.Property<int>("Grams")
                        .HasMaxLength(1000)
                        .HasColumnType("integer");

                    b.Property<int?>("MenuID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PicturePath")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Portion")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasMaxLength(100)
                        .HasColumnType("integer");

                    b.Property<int>("TotalCalories")
                        .HasColumnType("int");

                    b.HasKey("FoodID");

                    b.HasIndex("FoodCategoryID");

                    b.HasIndex("MenuID");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            Calories = 39,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Şeftali",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 2,
                            Calories = 69,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Üzüm",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 3,
                            Calories = 32,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Çilek",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 4,
                            Calories = 115,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Zeytin",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 5,
                            Calories = 89,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Muz",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 6,
                            Calories = 52,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Elma",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 7,
                            Calories = 47,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Portakal",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 8,
                            Calories = 53,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Mandalina",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 9,
                            Calories = 83,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Nar",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 10,
                            Calories = 29,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Limon",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 11,
                            Calories = 48,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Kayısı",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 12,
                            Calories = 74,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "İncir",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 13,
                            Calories = 46,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Erik",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 14,
                            Calories = 57,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Ayva",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 15,
                            Calories = 160,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Avakado",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 16,
                            Calories = 50,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Ananas",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 17,
                            Calories = 50,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Kiraz",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 18,
                            Calories = 61,
                            FoodCategoryID = 1,
                            Grams = 100,
                            Name = "Kivi",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 19,
                            Calories = 33,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Bamya",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 20,
                            Calories = 81,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Bezelye",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 21,
                            Calories = 27,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Biber",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 22,
                            Calories = 34,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Brokoli",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 23,
                            Calories = 18,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Domates",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 24,
                            Calories = 16,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Salatalık",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 25,
                            Calories = 47,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Enginar",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 26,
                            Calories = 41,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Havuç",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 27,
                            Calories = 23,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Ispanak",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 28,
                            Calories = 61,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Pırasa",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 29,
                            Calories = 26,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Kabak",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 30,
                            Calories = 77,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Patates",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 31,
                            Calories = 22,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Mantar",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 32,
                            Calories = 96,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Mısır",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 33,
                            Calories = 25,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Patlıcan",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 34,
                            Calories = 149,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Sarımsak",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 35,
                            Calories = 28,
                            FoodCategoryID = 2,
                            Grams = 100,
                            Name = "Turp",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 36,
                            Calories = 254,
                            FoodCategoryID = 3,
                            Grams = 100,
                            Name = "Hamburger",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 37,
                            Calories = 267,
                            FoodCategoryID = 3,
                            Grams = 100,
                            Name = "Double Cheeseburger",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 38,
                            Calories = 231,
                            FoodCategoryID = 3,
                            Grams = 100,
                            Name = "Burger King Whopper",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 39,
                            Calories = 263,
                            FoodCategoryID = 3,
                            Grams = 100,
                            Name = "McDonalds Cheeseburger",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 40,
                            Calories = 296,
                            FoodCategoryID = 3,
                            Grams = 100,
                            Name = "Tavuk Nugget",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 41,
                            Calories = 195,
                            FoodCategoryID = 3,
                            Grams = 100,
                            Name = "Fish and Chips",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 42,
                            Calories = 254,
                            FoodCategoryID = 3,
                            Grams = 100,
                            Name = "Patates Kızartması",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 43,
                            Calories = 256,
                            FoodCategoryID = 3,
                            Grams = 100,
                            Name = "McDonalds Big Mac",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 44,
                            Calories = 403,
                            FoodCategoryID = 4,
                            Grams = 100,
                            Name = "Cheddar",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 45,
                            Calories = 280,
                            FoodCategoryID = 4,
                            Grams = 100,
                            Name = "Mozzarella",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 46,
                            Calories = 337,
                            FoodCategoryID = 4,
                            Grams = 100,
                            Name = "Kaşar Peyniri",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 47,
                            Calories = 435,
                            FoodCategoryID = 4,
                            Grams = 100,
                            Name = "Eski Kaşar Peyniri",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 48,
                            Calories = 363,
                            FoodCategoryID = 4,
                            Grams = 100,
                            Name = "Tulum Peyniri",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 49,
                            Calories = 342,
                            FoodCategoryID = 4,
                            Grams = 100,
                            Name = "Krem Peynir",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 50,
                            Calories = 364,
                            FoodCategoryID = 4,
                            Grams = 100,
                            Name = "Keçi Peyniri",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 51,
                            Calories = 364,
                            FoodCategoryID = 4,
                            Grams = 100,
                            Name = "Koyun Peyniri",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 52,
                            Calories = 98,
                            FoodCategoryID = 4,
                            Grams = 100,
                            Name = "Cottage Peyniri",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 53,
                            Calories = 242,
                            FoodCategoryID = 5,
                            Grams = 100,
                            Name = "Biftek",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 54,
                            Calories = 121,
                            FoodCategoryID = 5,
                            Grams = 100,
                            Name = "Antrikot",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 55,
                            Calories = 138,
                            FoodCategoryID = 5,
                            Grams = 100,
                            Name = "Bonfile",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 56,
                            Calories = 189,
                            FoodCategoryID = 5,
                            Grams = 100,
                            Name = "Hindi",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 57,
                            Calories = 219,
                            FoodCategoryID = 5,
                            Grams = 100,
                            Name = "Tavuk",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 58,
                            Calories = 276,
                            FoodCategoryID = 5,
                            Grams = 100,
                            Name = "Kuzu Pirzola",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 59,
                            Calories = 196,
                            FoodCategoryID = 5,
                            Grams = 100,
                            Name = "Domuz Eti",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 60,
                            Calories = 156,
                            FoodCategoryID = 5,
                            Grams = 100,
                            Name = "Şinitzel",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 61,
                            Calories = 246,
                            FoodCategoryID = 5,
                            Grams = 100,
                            Name = "Dana Kıyma",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 62,
                            Calories = 230,
                            FoodCategoryID = 5,
                            Grams = 100,
                            Name = "Sosis",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 63,
                            Calories = 332,
                            FoodCategoryID = 5,
                            Grams = 100,
                            Name = "Sucuk",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 64,
                            Calories = 336,
                            FoodCategoryID = 5,
                            Grams = 100,
                            Name = "Salam",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 65,
                            Calories = 252,
                            FoodCategoryID = 6,
                            Grams = 100,
                            Name = "Kek",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 66,
                            Calories = 403,
                            FoodCategoryID = 6,
                            Grams = 100,
                            Name = "Donut",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 67,
                            Calories = 283,
                            FoodCategoryID = 6,
                            Grams = 100,
                            Name = "Tiramisu",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 68,
                            Calories = 312,
                            FoodCategoryID = 6,
                            Grams = 100,
                            Name = "Waffle",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 69,
                            Calories = 334,
                            FoodCategoryID = 6,
                            Grams = 100,
                            Name = "Profiterol",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 70,
                            Calories = 134,
                            FoodCategoryID = 6,
                            Grams = 100,
                            Name = "Sütlaç",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 71,
                            Calories = 402,
                            FoodCategoryID = 6,
                            Grams = 100,
                            Name = "Baklava",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 72,
                            Calories = 378,
                            FoodCategoryID = 6,
                            Grams = 100,
                            Name = "Muhallebi",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 73,
                            Calories = 251,
                            FoodCategoryID = 6,
                            Grams = 100,
                            Name = "Puding",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 74,
                            Calories = 42,
                            FoodCategoryID = 7,
                            Grams = 100,
                            Name = "Kola",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 75,
                            Calories = 35,
                            FoodCategoryID = 7,
                            Grams = 100,
                            Name = "Fanta",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 76,
                            Calories = 42,
                            FoodCategoryID = 7,
                            Grams = 100,
                            Name = "Sprite",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 77,
                            Calories = 35,
                            FoodCategoryID = 7,
                            Grams = 100,
                            Name = "Ayran",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 78,
                            Calories = 1,
                            FoodCategoryID = 7,
                            Grams = 100,
                            Name = "Çay",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 79,
                            Calories = 2,
                            FoodCategoryID = 7,
                            Grams = 100,
                            Name = "Kahve",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 80,
                            Calories = 36,
                            FoodCategoryID = 7,
                            Grams = 100,
                            Name = "IceTea",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 81,
                            Calories = 357,
                            FoodCategoryID = 8,
                            Grams = 100,
                            Name = "Arpa Şehriye",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 82,
                            Calories = 370,
                            FoodCategoryID = 8,
                            Grams = 100,
                            Name = "Noodle",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 83,
                            Calories = 260,
                            FoodCategoryID = 8,
                            Grams = 100,
                            Name = "Erişte",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 84,
                            Calories = 370,
                            FoodCategoryID = 8,
                            Grams = 100,
                            Name = "Makarna",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 85,
                            Calories = 200,
                            FoodCategoryID = 8,
                            Grams = 100,
                            Name = "Mantı",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 86,
                            Calories = 375,
                            FoodCategoryID = 8,
                            Grams = 100,
                            Name = "Yulaf Ezmesi",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 87,
                            Calories = 336,
                            FoodCategoryID = 8,
                            Grams = 100,
                            Name = "Müsli",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 88,
                            Calories = 357,
                            FoodCategoryID = 8,
                            Grams = 100,
                            Name = "Mısır Gevreği",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 89,
                            Calories = 364,
                            FoodCategoryID = 8,
                            Grams = 100,
                            Name = "Buğday Ezmesi",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 90,
                            Calories = 376,
                            FoodCategoryID = 8,
                            Grams = 100,
                            Name = "Kuskus",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 91,
                            Calories = 84,
                            FoodCategoryID = 9,
                            Grams = 100,
                            Name = "Bakla",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 92,
                            Calories = 127,
                            FoodCategoryID = 9,
                            Grams = 100,
                            Name = "Barbunya",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 93,
                            Calories = 164,
                            FoodCategoryID = 9,
                            Grams = 100,
                            Name = "Nohut",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 94,
                            Calories = 341,
                            FoodCategoryID = 9,
                            Grams = 100,
                            Name = "Kuru Fasulye",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 95,
                            Calories = 353,
                            FoodCategoryID = 9,
                            Grams = 100,
                            Name = "Mercimek",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 96,
                            Calories = 31,
                            FoodCategoryID = 9,
                            Grams = 100,
                            Name = "Yeşil Fasulye",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 97,
                            Calories = 135,
                            FoodCategoryID = 9,
                            Grams = 100,
                            Name = "Börülce",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 98,
                            Calories = 884,
                            FoodCategoryID = 10,
                            Grams = 100,
                            Name = "Zeytinyağı",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 99,
                            Calories = 884,
                            FoodCategoryID = 10,
                            Grams = 100,
                            Name = "Ayçiçekyağı",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 100,
                            Calories = 884,
                            FoodCategoryID = 10,
                            Grams = 100,
                            Name = "Kanola Yağı",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 101,
                            Calories = 876,
                            FoodCategoryID = 10,
                            Grams = 100,
                            Name = "Tereyağı",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 102,
                            Calories = 717,
                            FoodCategoryID = 10,
                            Grams = 100,
                            Name = "Margarin",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 103,
                            Calories = 884,
                            FoodCategoryID = 10,
                            Grams = 100,
                            Name = "PalmYağı",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 104,
                            Calories = 884,
                            FoodCategoryID = 10,
                            Grams = 100,
                            Name = "SusamYağı",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 105,
                            Calories = 496,
                            FoodCategoryID = 11,
                            Grams = 100,
                            Name = "Süt Tozu",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 106,
                            Calories = 112,
                            FoodCategoryID = 11,
                            Grams = 100,
                            Name = "Cacık",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 107,
                            Calories = 51,
                            FoodCategoryID = 11,
                            Grams = 100,
                            Name = "Kefir",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 108,
                            Calories = 345,
                            FoodCategoryID = 11,
                            Grams = 100,
                            Name = "Krema",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 109,
                            Calories = 90,
                            FoodCategoryID = 11,
                            Grams = 100,
                            Name = "Sıcak Çikolata",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 110,
                            Calories = 13,
                            FoodCategoryID = 11,
                            Grams = 100,
                            Name = "Badem Sütü",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 111,
                            Calories = 61,
                            FoodCategoryID = 11,
                            Grams = 100,
                            Name = "Tam Yağlı Süt",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 112,
                            Calories = 50,
                            FoodCategoryID = 11,
                            Grams = 100,
                            Name = "Az Yağlı Süt",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 113,
                            Calories = 42,
                            FoodCategoryID = 11,
                            Grams = 100,
                            Name = "Yarım Yağlı Süt",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 114,
                            Calories = 266,
                            FoodCategoryID = 12,
                            Grams = 100,
                            Name = "Beyaz Ekmek",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 115,
                            Calories = 220,
                            FoodCategoryID = 12,
                            Grams = 100,
                            Name = "Çavdarlı Ekmek",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 116,
                            Calories = 247,
                            FoodCategoryID = 12,
                            Grams = 100,
                            Name = "Tam Tahıllı Ekmek",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 117,
                            Calories = 406,
                            FoodCategoryID = 12,
                            Grams = 100,
                            Name = "Kruvasan",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 118,
                            Calories = 208,
                            FoodCategoryID = 12,
                            Grams = 100,
                            Name = "Su Böreği",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 119,
                            Calories = 193,
                            FoodCategoryID = 12,
                            Grams = 100,
                            Name = "Tost",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        },
                        new
                        {
                            FoodID = 120,
                            Calories = 224,
                            FoodCategoryID = 12,
                            Grams = 100,
                            Name = "Poğaça",
                            Portion = 2,
                            Quantity = 1,
                            TotalCalories = 0
                        });
                });

            modelBuilder.Entity("Diet_Models.Concretes.Menu", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuID"));

                    b.Property<DateTime>("MealDate")
                        .HasColumnType("datetime");

                    b.Property<int>("MealID")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<int?>("TotalCaloriesByMeal")
                        .HasMaxLength(5000)
                        .HasColumnType("integer");

                    b.HasKey("MenuID");

                    b.HasIndex("MealID");

                    b.HasIndex("PersonID");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Diet_Models.Concretes.Food", b =>
                {
                    b.HasOne("CalorieProject_Models.Concretes.FoodCategory", "FoodCategory")
                        .WithMany("Foods")
                        .HasForeignKey("FoodCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diet_Models.Concretes.Menu", "Menu")
                        .WithMany("Foods")
                        .HasForeignKey("MenuID");

                    b.Navigation("FoodCategory");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Diet_Models.Concretes.Menu", b =>
                {
                    b.HasOne("CalorieProject_Models.Concretes.Meal", "Meal")
                        .WithMany("Menu")
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieProject_Models.Concretes.Person", "Person")
                        .WithMany("Menus")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CalorieProject_Models.Concretes.FoodCategory", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("CalorieProject_Models.Concretes.Meal", b =>
                {
                    b.Navigation("Menu");
                });

            modelBuilder.Entity("CalorieProject_Models.Concretes.Person", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("Diet_Models.Concretes.Menu", b =>
                {
                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
